@columnizeFast { dependencies: @strlen
  @columnizeFast usage: sourceVar
  // returns      : sourceVar.c
  // optional arguments are positional. IE, xPos cannot be supplied without first supplying yPos
  // strip leading whitespace
  // expand sourceVar
  Set "_=^!@.args:~1^!"
  // get length
  !@strlen! _ $len
  Set "_=^!_:~0,1^![B[D^!_:~1,1^![B[D^!_:~2,1^![B[D^!_:~3,1^![B[D^!_:~4,1^![B[D^!_:~5,1^![B[D^!_:~6,1^![B[D^!_:~7,1^![B[D^!_:~8,1^![B[D^!_:~9,1^![B[D^!_:~10,1^![B[D^!_:~11,1^![B[D^!_:~12,1^![B[D^!_:~13,1^![B[D^!_:~14,1^![B[D^!_:~15,1^![B[D^!_:~16,1^![B[D^!_:~17,1^![B[D^!_:~18,1^![B[D^!_:~19,1^![B[D^!_:~20,1^![B[D^!_:~21,1^![B[D^!_:~22,1^![B[D^!_:~23,1^![B[D^!_:~24,1^![B[D^!_:~25,1^![B[D^!_:~26,1^![B[D^!_:~27,1^![B[D^!_:~28,1^![B[D^!_:~29,1^![B[D^!_:~30,1^![B[D^!_:~31,1^![B[D^!_:~32,1^![B[D^!_:~33,1^![B[D^!_:~34,1^![B[D^!_:~35,1^![B[D^!_:~36,1^![B[D^!_:~37,1^![B[D^!_:~38,1^![B[D^!_:~39,1^![B[D^!_:~40,1^![B[D^!_:~41,1^![B[D^!_:~42,1^![B[D^!_:~43,1^![B[D^!_:~44,1^![B[D^!_:~45,1^![B[D^!_:~46,1^![B[D^!_:~47,1^![B[D^!_:~48,1^![B[D^!_:~49,1^![B[D^!_:~50,1^![B[D"
  Set /a "$len*=7"
  For %%i in ("^!$len^!")Do Set "$columnizeFast=^!_:~0,%%~i^!"
} @columnizeFast /args 