@fillRect {
  @fillRect usage: %@fillRect% <returnVar> <height> <width> [color]

<; Constructs a rectangle using the properties of the args provided.
   Author: T3RRY
   Note  : \E variable contains the Escape character U+001b ; Defined by automacro.bat
   https://github.com/T3RRYT3RR0R/Automacro/blob/main/AutoMacro/Examples/automacro.bat
;>
  // $set : Defines the variable prior to macro definition; excludes the set command from macro
  $Set "@.Substring=                "

  // square the length of @.substring = length of 256 characters
  set "@.height=^!@.substring: =                ^!"

  // tokenise processed args for substituion within DE variable
  For /f "tokens=1,2,3,4" %%1 in ("^!@.args^!")Do (
    // trim string to height 
    set "@.height=^!@.height:~0,%%2^!"

    // populate height with fill lines
    If not "%%~4" == "" (
      set "%%1=!\E![48;5;%%4m^!@.height: =!\E![%%3X!\E![B^!!\E![0m"
    )Else set "%%1=^!@.height: =!\E![%%3X!\E![B^!!\E![0m"

  )
} @fillRect /args /selfRef