@range {
  @range usage: %@range% <ReturnVar> <min> <max> <TestValue|testSum>
  //   case  true: 1
  //   case false: 0
  For /f "tokens=1 delims= " %%1 in ("@^!@.args^!")Do Set "$ranges=%%~1"
  Set ^"$range=^!@.Args:"=^!"
  For /f "tokens=1,2,3,* delims= " %%1 in ("^!$range^!")Do Set /a "%%1=((((((%%~4)-%%~2)>>31)+((%%~3-(%%~4))>>31)))>>31)+1" || (
    Echo(invalid arguments: ^!@.args^!
    Echo(^!@range_usage^!
  )
} @range /args
