@alignRight { dependencies: @strlen
  @alignRight usage: %@alignRight% <Xright> <stringVar> <returnVar> ["yPos"]

  // split arg variables and optional integer/sum for yPos
  For /f "tokens=1,2,3,* delims= " %%1 in ("^!@.args^!")Do (

    // Get length of string
    !@strlen! %%~2 $len

    // calculate x position
    Set /a "$right=((%%~1)-$len)-1"

    // apply position via VT absolute column sequence
    Set "%%3=[^!$right^!G^!%%2^!"

    // process optional arg if supplied for yPos
    If not "%%~4" == "" (
     Set /a "$right.y=(%%~4)"

     // prepend reutrn var with VT absolute row sequence
     Set "%%3=[^!$right.y^!d^!%%3^!"
    )
  )
} @alignRight /args /help