@columnate { dependencies: @strlen
  @columnate usage: %@columnate% <sourceVar> [yPos] [xPos] [FGcolor] [BGcolor] [/D]
  @columnate usage: /D : doubles the width and height of the font
  @columnate usage: macro returns:
  @columnate usage:   sourceVar.c : the vertically formatted output string
  @columnate usage:   $reset.size : contains the vt sequence needed to restore default font size.
  @columnate usage:   [optional arguments] are positional. IE, xPos cannot be supplied without first supplying yPos

  $Set "$reset.size=#5"
  If not "^!@.args: /D=^!" == "^!@.args^!" (
    Set "@.args=^!@.args: /D=^!"
    Set "@.switch[D]=true"
  )Else Set "@.switch[D]="

  For /f "tokens=2,3,4,5,6 delims= " %%1 in ("@^!@.args^!") Do (
    Set "@.t=^!%%~1^!"
    !@strlen! @.t $len
    Set "@.x="
    Set "@.y="
    Set "@.FG="
    Set "@.BG="
    If not "%%~2" == "" Set "@.x=[%%~2d"
    If not "%%~3" == "" Set "@.y=[%%~3G"
    If not "%%~4" == "" Set "@.FG=[38;5;%%~4m"
    If not "%%~5" == "" Set "@.BG=[48;5;%%~5m"
    Set "%%~1.c=^!@.y^!^!@.x^!^!@.FG^!^!@.BG^!"

    For /l %%i in (0 1 ^!$len^!)Do (
      If defined @.switch[D] (
        Set "%%~1.c=^!%%~1.c^!#3^!@.t:~%%i,1^![B[D#4^!@.t:~%%i,1^![B[D"
      )Else (
        Set "%%~1.c=^!%%~1.c^!^!@.t:~%%i,1^![B[D"
      )
    )
    Set "%%~1.c=^!%%~1.c^![0m"
  )
} @columnate /args /selfref

<; notes:
  Author T3RRY
  Version 1.0 04/08/2024
;>