@first { dependencies: @strlen
  @first usage: %@first% <varname> <"delimChar">
  // returns : $first
  For /f "tokens=1,* delims= " %%1 in ("^!@.args^!")Do (
    !@strlen! %%1 $len
    Set "$char=^^^%%~2"
    Set "$char=^!$char:~-1^!"
    Set "@.t=^!%%1^!"
    Set "$first="
    For /l %%i in (0 1 ^!$len^!)Do if not defined $first (
      If "^!@.t:~%%i,1^!" == "^!$char^!" (
        Set "$first=^!@.t:~0,%%i^!"
      )
    )
  )
} @first /args