@waveprint { dependencies: @strlen
  @waveprint usage: <sourceVar> <x> <y> <waveheight> returns = $wavePrint
  Set "$wavePrint="
  For /f "tokens=1,2,3,4,*" %%1 in ("^!@.args^!") Do (
    !@strlen! %%1 $len
    Set yDir=+
    Set /a "y.ubound=(%%3 - (%%4/2)),y.lBound=(%%3 + (%%4/2)),@.y=y.uBound,@.x=%%2"
    For /l %%i in (0 1 ^!$len^!)Do if not "^!%%1:~%%i,1^!" == "" (
      Set "$wavePrint=^!$wavePrint^![^!@.y^!;^!@.x^!H^!%%1:~%%i,1^!"
      Set /a "@.y^!yDir^!=1,@.x+=1"
      If ^!@.y^! LEQ ^!y.uBound^! Set "yDir=+"
      If ^!@.y^! GEQ ^!y.lBound^! Set "yDir=-"
    )
    If not "%%~5" == "" Set "$wavePrint=[%%~5m^!$wavePrint^!"
  )
 } @waveprint /args

